function doMultiSelect(tablename,condition,columnName,colModelStr,displaycolumn){
	DialogUtil.openModalWindow("/WebConnector/multiselect.jsp",{tablename:tablename,condition:condition,columnName:columnName,colModelStr:colModelStr,displaycolumn:displaycolumn},{EVENT_OK:function(param){
	 	//alert('这是父窗体 子窗体返回的是:'+param);
 	}},750,350);
}
/**
 * 封装了不同table所需的jsFile,dwrClass,dwrFun,dwrCountFun,colNames,colModel,searchList
 */
var selectTable={
	operator:{
	        jsFile:'OperatorService.js',
	        dwrClass:'OperatorService',
	        dwrFun:'findMapByPropertiesWithLimit',
	   		dwrCountFun:'findCountByProperties',
	   		colNames:['ID','部门名称','所属单位'],
	   		condition:'',
	   		colModel:[{
	   			name:'operatorCode',
	   			index:'operatorCode',
	   			key:true,
	   			hidden:false
	   		},{
	   			name:'operatorName',
	   			index:'operatorName',
	   			hidden:false
	   		},{
	   			name:'organization',
	   			index:'organization',
	   			hidden:false
	   		}],
	   		displaycolumn:'organization',//显示在已选框中的列
	   		searchList:[{//查询框所需
	   			text:'编号',//显示的查询项
	   			value:'operatorCode'//对应的数据库列名
   			}]
	},
	article:{
	        jsFile:'ArticleService.js',
	        dwrClass:'ArticleService',
	        dwrFun:'findMapByPropertiesWithLimit',
	   		dwrCountFun:'findCountByProperties',
	   		colNames:['ID','标题','内容'],
	   		condition:'',
	   		colModel:[{
	   			name:'articleID',
	   			index:'articleID',
	   			key:true,
	   			hidden:true
	   		},{
	   			name:'title',
	   			index:'title',
	   			hidden:false
	   		},{
	   			name:'content',
	   			index:'content',
	   			hidden:false
	   		}],
	   		displaycolumn:'title',//显示在已选框中的列
	   		searchList:[{
	   			text:'标题',//显示的查询项
	   			value:'title'//对应的数据库列名
   			}]
	},
	course:{
	        jsFile:'CourseService.js',
	        dwrClass:'CourseService',
	        dwrFun:'findMapByPropertiesWithLimit',
	   		dwrCountFun:'findCountByProperties',
	   		colNames:['ID','课程代号','课程名称','第几册','课程类型'],
	   		condition:'',
	   		colModel:[{
	   			name:'courseID',
	   			index:'courseID',
	   			key:true,
	   			hidden:true
	   		},{
	   			name:'courseCode',
	   			index:'courseCode'
	   		},{
	   			name:'courseName',
	   			index:'courseName'
	   		},{
	   			name:'courseOrder',
	   			index:'courseOrder'
	   		},{
	   			name:'courseType',
	   			index:'courseType'
	   		}],
	   		displaycolumn:'courseName',//显示在已选框中的列
	   		searchList:[{
	   			text:'课程名称',//显示的查询项
	   			value:'courseName'//对应的数据库列名
   			}]
   			
	}
}
